// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM5UvYb-rV_f8aWWWVm5MYGLh0g_ZyCW8',
    appId: '1:457167475699:web:46b1b7638875dc8436f886',
    messagingSenderId: '457167475699',
    projectId: 'katering-app-b6e3a',
    authDomain: 'katering-app-b6e3a.firebaseapp.com',
    storageBucket: 'katering-app-b6e3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZvLHEKIkleWPRuvkMij3eV0GfIJtfmc',
    appId: '1:457167475699:android:98932ed4c0767e3736f886',
    messagingSenderId: '457167475699',
    projectId: 'katering-app-b6e3a',
    storageBucket: 'katering-app-b6e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkbuOtleh7dca1asJK-bAwFv--CiD4xxo',
    appId: '1:457167475699:ios:b40d430db6f0761436f886',
    messagingSenderId: '457167475699',
    projectId: 'katering-app-b6e3a',
    storageBucket: 'katering-app-b6e3a.firebasestorage.app',
    iosBundleId: 'com.example.kateringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkbuOtleh7dca1asJK-bAwFv--CiD4xxo',
    appId: '1:457167475699:ios:b40d430db6f0761436f886',
    messagingSenderId: '457167475699',
    projectId: 'katering-app-b6e3a',
    storageBucket: 'katering-app-b6e3a.firebasestorage.app',
    iosBundleId: 'com.example.kateringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM5UvYb-rV_f8aWWWVm5MYGLh0g_ZyCW8',
    appId: '1:457167475699:web:c8267cd0225e0f5236f886',
    messagingSenderId: '457167475699',
    projectId: 'katering-app-b6e3a',
    authDomain: 'katering-app-b6e3a.firebaseapp.com',
    storageBucket: 'katering-app-b6e3a.firebasestorage.app',
  );

}